options:
	prefix: &f

command /customitems [<text>] [<player>]:
	permission: admin
	trigger:
		if arg-1 is "pets.pug":
			give player 1 paper named "&fCarlin" with custom model data 10122
            

on rightclick:

#pets.pug
    if player's tool is paper with custom model data 10122:
        remove 1 of paper with custom model data 10122 from player's inventory
        execute console command "lp user %player% permission set pets.pug"
